prove-all: tidy

diff --git a/libexec/klab-prove b/libexec/klab-prove
--- a/libexec/klab-prove
+++ b/libexec/klab-prove
@@ -10,7 +10,7 @@ reset=$(tput sgr0)
 
 # parse args
 usage() { echo "Usage: klab prove [-d] [<spec>]" 1>&2; exit 1; }
-OPTS=`getopt -o "d" -l "dump" -- "$@"`
+OPTS=`getopt -o "d" -l "dump" -o "l" -l "logs" -- "$@"`
 dump=false
 if [ $? != 0 ]
 then
@@ -18,11 +18,12 @@ then
 fi
 eval set -- "$OPTS"
 while true; do
-    case "$1" in
-	-d | --dump)  dump=true; shift;;
+  case "$1" in
+	-d | --dump) dump=true; shift;;
+  --logs)      logs=true; shift;;
 	--)           shift; break;;
 	*)            usage
-    esac
+  esac
 done
 
 export KLAB_OUT=${KLAB_OUT:-out}
@@ -34,7 +35,7 @@ if [ -z "$KLAB_EVMS_PATH" ]; then
 fi
 echo "Using evm-semantics from $KLAB_EVMS_PATH"
 
-if [ ! -z "$QUIET" ]; then
+if [ ! -z "$logs" ]; then
   mkdir -p $KLAB_OUT/log/
   STDOUT="$KLAB_OUT/log/$spec_hash.log"
   STDERR="$KLAB_OUT/log/$spec_hash.err.log"
@@ -99,19 +100,22 @@ kprove() {
   exit $?
 }
 
-_term() {
-  echo "Trapped SIG$(kill -l $?) in klab prove."
-  if [ -n "$kprove_child" ]; then
-    echo "Sending SIGTERM to $kprove_child in klab prove."
-    kill -s TERM "$kprove_child"
+try_kill() {
+  if [ -n "$1" ]; then
+    echo "[prove] Sending SIGTERM to $1."
+    pkill -x "$1" && echo "[prove] Sent SIGTERM to $1." || echo "[prove] unable to kill $1"
   fi;
 }
-trap _term TERM INT
+
+_term() {
+  echo "[prove] Trapped SIG$(kill -l $?)."
+  try_kill $kprove_child
+}
+trap _term SIGTERM SIGINT
 
 echo "${blue}Proof ${bold}STARTING${reset}:" "$(basename "$target_spec")" "[$spec_name]" "$dump_notice"
 set +e
-kprove "$target_spec" >"$STDOUT" 2>"$STDERR" &
-kprove_child=$!
+kprove "$target_spec" >"$STDOUT" 2>"$STDERR" & kprove_child=$!
 wait "$kprove_child"
 result=$?
 unset kprove_child
diff --git a/libexec/klab-prove-all b/libexec/klab-prove-all
--- a/libexec/klab-prove-all
+++ b/libexec/klab-prove-all
@@ -6,6 +6,7 @@ green=$(tput setaf 2)
 yellow=$(tput setaf 3)
 bold=$(tput bold)
 reset=$(tput sgr0)
+export red green yellow bold reset
 
 if [ -z "$KLAB_OUT" ]; then
   echo "KLAB_OUT not set, defaulting to ./out/"
@@ -29,13 +30,13 @@ export RUNNING_DIR=$KLAB_OUT/meta/running
 export OBLIGATIONS=$KLAB_OUT/obligations.batch
 export BATCH_LIMIT=8
 export THREADS=${THREADS:-2}
-export QUIET=1
 PNAME=$(jq -r '.name' < config.json)
 if [ "$PNAME" == "null" ]; then PNAME=""; fi
 export PNAME
 
 if [ -d ".git" ]; then
-  export build_hash=$(klab get-build-id)
+  build_hash=$(klab get-build-id)
+  export build_hash
   if [ -n "$KLAB_REPORT_DIR" ]; then
     export KLAB_REPORT_NAME_DIR=$KLAB_REPORT_DIR/$PNAME
     export KLAB_REPORT_PROJECT_DIR=$KLAB_REPORT_DIR/$PNAME/$build_hash
@@ -46,24 +47,24 @@ if [ -d ".git" ]; then
     if [ ! -f "$KLAB_REPORT_DIR/$PNAME"/report.json ]; then
       echo "{}" > "$KLAB_REPORT_DIR/$PNAME"/report.json
     fi;
-    jq -r '.src.rules[]' < config.json |xargs -I {} cp {} $KLAB_REPORT_PROJECT_DIR
-    jq -r '.src.smt_prelude' < config.json |xargs -I {} cp {} $KLAB_REPORT_PROJECT_DIR
+    jq -r '.src.rules[]' < config.json |xargs -I {} cp {} "$KLAB_REPORT_PROJECT_DIR"
+    jq -r '.src.smt_prelude' < config.json |xargs -I {} cp {} "$KLAB_REPORT_PROJECT_DIR"
   fi;
 fi;
 
 report () {
   set -e
-  if [ ! -z $KLAB_REPORT_NAME_DIR ]; then
+  if [ ! -z "$KLAB_REPORT_NAME_DIR" ]; then
     exec 3>"$KLAB_REPORT_NAME_DIR"/report.json.lock
     flock -x 3 || exit 0
   fi;
   klab report
   if [ -n "$KLAB_REPORT_PROJECT_DIR" ]; then
     cp "$KLAB_OUT/report/index.html" "$KLAB_REPORT_PROJECT_DIR"
-    cat <<< $(jq -s '.[0] * .[1]' "$KLAB_REPORT_DIR/$PNAME"/report.json "$KLAB_OUT"/report/report.json) > "$KLAB_REPORT_DIR/$PNAME"/report.json
+    cat <<< $(jq -s '.[0] * .[1]' "$KLAB_REPORT_DIR/$PNAME/report.json" "$KLAB_OUT/report/report.json") > "$KLAB_REPORT_DIR/$PNAME/report.json"
     echo "Report exported to $KLAB_REPORT_PROJECT_DIR"
   fi;
-  if [ ! -z $KLAB_REPORT_NAME_DIR ]; then
+  if [ ! -z "$KLAB_REPORT_NAME_DIR" ]; then
     exec 3>&-
   fi;
 }
@@ -73,75 +74,75 @@ export -f report
 do_proof () {
   set -e
 
-  timeout () {
-    echo "Trapped SIGTERM in do_proof()."
-    if [ -n "$proof_child" ]; then
-      echo "Sending SIGTERM to $proof_child in do_proof()."
-      kill -s TERM "$proof_child"
-    fi;
-    # check if SIGTERM is due to timeout
-    # if [ -n "$PROOF_START" ] && (( ($(date +%s) - PROOF_START) < TIMEOUT )); then
-    #   echo "Cause of death wasn't timeout, exiting without further action."
-    #   exit 1
-    # fi;
-    echo "Cause of death was timeout."
+  name=$1
+  hash=$(klab hash "$name")
+
+  if [[ $name =~ .*_pass$ ]] || [[ $name =~ .*_pass_oog$ ]] ; then
+    # do not dump _pass.k or pass_oog.k
+    PROVE_DUMP=""
+  else
+    PROVE_DUMP="--dump"
+  fi;
+
+  _post_timeout () {
+    echo "[do_proof] Timeout cleanup..."
+    local hash=$1
     if [ -n "$hash" ]; then
       touch "$KLAB_OUT/timeout/$hash";
       klab get-lemmas "$hash"
       klab zip "$hash" > /dev/null
-      echo "Zipped timed-out proof log for $hash."
+      echo "[do_proof] Zipped timed-out proof log for $hash."
       if [ -n "$KLAB_REPORT_NAME_DIR" ]; then
         cp "$KLAB_OUT/log/${hash}.zip" "$KLAB_REPORT_NAME_DIR"
       fi;
-      echo "Saved time-out proof log for $hash."
+      echo "[do_proof] Saved time-out proof log for $hash."
+    fi;
+    echo "[DEBUG] finished timeout cleanup"
+  }
+  try_kill() {
+    if [ -n "$1" ]; then
+      echo "[do_proof] Sending SIGTERM to $1"
+      pkill -x "$1" && echo "[do_proof] killed $1" || echo "[do_proof] unable to kill $1"
     fi;
   }
-  trap timeout TERM
+  _sig_term () {
+    echo "[do_proof] Trapped SIGTERM."
+    try_kill "$proof_child"
+    _post_timeout "$hash"
+  }
+  trap _sig_term TERM
+  _sig_int () {
+    echo "[do_proof] Trapped SIGINT."
+    try_kill "$proof_child"
+    exit 1
+  }
+  trap _sig_int INT
 
-  TIMER="/usr/bin/env time --quiet"
-  # get the proof hash
-  hash=$(klab hash "$1")
-  # remember the name - first argument
-  name=$1
-  # report run
-  touch "$RUNNING_DIR/$hash"
+  TIMER="/usr/bin/env time --quiet -o $KLAB_OUT/meta/time/$hash"
+
+  # report start
   report
-  if [[ $name =~ .*_pass$ ]] || [[ $name =~ .*_pass_oog$ ]] ; then
-    # do not dump _pass.k or pass_oog.k
-    PROVE_FLAGS=""
-  else
-    PROVE_FLAGS="--dump"
-  fi;
+  touch "$RUNNING_DIR/$hash"
+
   set +e
-  # run proof
-  PROOF_START=$(date +%s)
-  export PROOF_START
-  $TIMER -o "$KLAB_OUT/meta/time/$hash" klab prove $PROVE_FLAGS "$hash" &
-  proof_child=$!
+
+  $TIMER klab prove $PROVE_DUMP --logs "$hash" & proof_child=$!
   wait "$proof_child"
   result=$?
   unset proof_child
-  unset PROOF_START
-  if [ $result -ne "0" ]; then
-    cat "$KLAB_OUT/log/${hash}.log"
-    cat "$KLAB_OUT/log/${hash}.err.log"
-  fi;
-  if [ $result -ne "0" ] && [ -z $PROVE_FLAGS ]; then
-    # run proof again with --dump if necessary
-    PROVE_FLAGS="--dump"
-    PROOF_START=$(date +%s)
-    export PROOF_START
-    $TIMER -o "$KLAB_OUT/meta/time/$hash" klab prove $PROVE_FLAGS "$hash" &
-    proof_child=$!
+
+  if [ $result -ne "0" ] && [ -z $PROVE_DUMP ]; then
+    $TIMER klab prove --dump --logs "$hash" & proof_child=$!
     wait "$proof_child"
     result=$?
     unset proof_child
-    unset PROOF_START
   fi;
   set -e
+
   # report finish
   rm "$RUNNING_DIR/$hash"
   report
+
   if [[ $name =~ .*_pass_rough$ ]] && [ $result -eq "0" ]; then
     # gas analysis from the rough pass
     klab get-gas "$hash"
@@ -196,8 +197,6 @@ make_batch () {
   TIMEOUTTIMEOUT=600000
   export TIMEOUTTIMEOUT
   parallel -u --timeout $TIMEOUT --termseq TERM,$TIMEOUTTIMEOUT,KILL,25 -P "$THREADS" do_proof {} < "$OBLIGATIONS"
-  # previously used:
-  # xargs -P "$THREADS" -I % sh -xc 'do_proof %' < "$OBLIGATIONS"
   result=$?
   echo $result
   if [ $result -ge 255 ]; then
@@ -218,9 +217,9 @@ mkdir -p "$KLAB_OUT/timeout"
 rm -fdr "$KLAB_OUT/meta/name"
 rm -fdr "$KLAB_OUT/specs"
 klab build
-if [ ! -z $KLAB_REPORT_NAME_DIR ]; then
-  rm -f $KLAB_REPORT_NAME_DIR/latest
-  ln -s $KLAB_REPORT_PROJECT_DIR $KLAB_REPORT_NAME_DIR/latest
+if [ ! -z "$KLAB_REPORT_NAME_DIR" ]; then
+  rm -f "$KLAB_REPORT_NAME_DIR/latest"
+  ln -s "$KLAB_REPORT_PROJECT_DIR" "$KLAB_REPORT_NAME_DIR/latest"
 fi
 if [ -n "$KLAB_REPORT_PROJECT_DIR" ] && [ -f "$KLAB_OUT/bin_runtime.k" ]; then
   cp "$KLAB_OUT/bin_runtime.k" "$KLAB_REPORT_PROJECT_DIR"
@@ -250,4 +249,3 @@ if [ $failures -ge 1 ]; then
 else
   exit 0
 fi;
-
