fix klab-hash from head and prove from path bugs

diff --git a/libexec/klab-hash b/libexec/klab-hash
--- a/libexec/klab-hash
+++ b/libexec/klab-hash
@@ -1,16 +1,26 @@
 #!/usr/bin/env bash
 
-name=$1
-
 if [ -z "$KLAB_OUT" ]; then
   KLAB_OUT=out
 fi
 
-if [ -f "$KLAB_OUT/meta/name/$name" ]; then
-  hash=$(cat "$KLAB_OUT/meta/name/$name")
+if [ -z "$1" ]; then
+  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
+  if [ -z $spec_hash ]; then
+    echo "ERROR: $1 no spec or active HEAD found"
+    exit 1;
+  fi
 else
-  echo "ERROR: $name is unknown"
-  exit 1;
-fi;
+  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
+    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  else
+    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
+      spec_hash="$1"
+    else
+      echo "ERROR: $1 is unknown"
+      exit 1;
+    fi;
+  fi;
+fi
 
-echo "$hash";
+echo "$spec_hash";
