changes interface to be based on focused out/HEAD

diff --git a/libexec/klab-get-gas b/libexec/klab-get-gas
--- a/libexec/klab-get-gas
+++ b/libexec/klab-get-gas
@@ -1,83 +1,34 @@
-#!/usr/bin/env node
-// TODO - compile needs to carry on the act
+#!/usr/bin/env bash
 
-const fs = require("fs");
-const path = require("path");
-const {docopt}      = require("docopt");
-const {
-  testPath,
-  read,
-  ensureDir
-} = require("../lib/util.js");
-const getGasExpr = require('../lib/gas.js');
-const { deltaCC } = require("../lib/constraints.js")
-const kast = require("../lib/kast.js")
+if [ -z "$KLAB_OUT" ]; then
+  KLAB_OUT=out
+fi
+export GAS_DIR=$KLAB_OUT/gas
 
-const KLAB_OUT = process.env.KLAB_OUT || "out";
-const KLAB_WD_PATH = path.join(KLAB_OUT, "data");
+if [ -z "$1" ]; then
+  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
+  if [ -z $spec_hash ]; then
+    echo "ERROR: $1 no spec or active HEAD found"
+    exit 1;
+  fi
+else
+  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
+    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  else
+    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
+      spec_hash="$1"
+    else
+      echo "ERROR: $1 is unknown"
+      exit 1;
+    fi;
+  fi;
+fi
 
-const usage = `
-Usage:
-  klab get-gas [options] <hash>
-`
+klab get-x "ethereum.evm.callState.gas" $spec_hash > "$GAS_DIR/${spec_hash}.raw.kast.json"
+result=$?
 
-const cmd = docopt(usage, {
-  argv: ["get-gas"].concat(process.argv.slice(2))
-});
-const proofid = cmd['<hash>']
+if [ $result -ne "0" ]; then
+  rm "$GAS_DIR/${spec_hash}.raw.kast.json"
+  exit 1;
+fi
 
-const {
-  prune_edges
-} = require("../lib/compile.js");
-
-const {pruned_edges, initt, finished} = prune_edges(proofid, false);
-
-const if_else_fi = args => ({
-  node: "KApply",
-  label: "#if_#then_#else_#fi_K-EQUAL",
-  variable: false,
-  arity: 3,
-  args: args
-})
-const or = args => ({
-  node: "KApply",
-  label: "_andBool_",
-  variable: false,
-  arity: 2,
-  args: args
-})
-
-const blob = blobid => JSON.parse(read(path.join(KLAB_WD_PATH, proofid + "_blobs", blobid + ".json")));
-
-const E = pruned_edges;
-const traverse = (firstNode) => {
-  var c = firstNode;
-  while(c in E && E[c].length == 1) {
-    c = E[c][0].to;
-  }
-  if (!(c in E) || E[c].length == 0) {
-    return kast.get(blob(c.split('_')[0]).term, "ethereum.evm.callState.gas")
-  } else {
-    const l = traverse(E[c][0].to);
-    const r = traverse(E[c][1].to);
-
-    if(l.label && l.label == "#if_#then_#else_#fi_K-EQUAL" && JSON.stringify(l.args[2]) == JSON.stringify(r)) {
-      return if_else_fi([
-        or([
-          deltaCC(blob(E[c][0].from.split('_')[1]), blob(E[c][0].to.split('_')[1]))[0],
-          l.args[0]
-        ]),
-        l.args[1],
-        r
-      ])
-    }
-
-    return JSON.stringify(l) == JSON.stringify(r)
-      ? r
-      : if_else_fi([
-        deltaCC(blob(E[c][0].from.split('_')[1]), blob(E[c][0].to.split('_')[1]))[0], l, r
-      ])
-  }
-}
-
-console.log(JSON.stringify(traverse(initt)));
diff --git a/libexec/klab-hash b/libexec/klab-hash
--- a/libexec/klab-hash
+++ b/libexec/klab-hash
@@ -1,31 +1,16 @@
-#!/usr/bin/env node
-const fs            = require("fs");
-const {docopt}      = require("docopt");
-const path          = require('path');
-const {
-  testPath,
-  read,
-  warn
-} = require("../lib/util.js");
+#!/usr/bin/env bash
 
-const KLAB_OUT     = process.env.KLAB_OUT || "out";
+name=$1
 
-const usage = `
-Usage:
-  klab hash [options] <spec>
-`
+if [ -z "$KLAB_OUT" ]; then
+  KLAB_OUT=out
+fi
 
-const cmd = docopt(usage, {
-  argv: ["hash"].concat(process.argv.slice(2))
-});
+if [ -f "$KLAB_OUT/meta/name/$name" ]; then
+  hash=$(cat "$KLAB_OUT/meta/name/$name")
+else
+  echo "ERROR: $name is unknown"
+  exit 1;
+fi;
 
-const spec = cmd["<spec>"];
-const name = path.basename(spec, '.k');
-
-const hash_path = path.join(KLAB_OUT, 'meta', 'name', name);
-
-if(!testPath(hash_path)) {
-  fs.writeFileSync(hash_path, name);
-  warn(`No hash found, writing debug output under ${name}`);
-}
-process.stdout.write(read(hash_path))
+echo "$hash";
diff --git a/libexec/klab-solve-gas b/libexec/klab-solve-gas
--- a/libexec/klab-solve-gas
+++ b/libexec/klab-solve-gas
@@ -1,15 +1,33 @@
 #!/usr/bin/env bash
-GAS_SOLVER="${GAS_SOLVER:-${0%/*/*}/libexec/klab-gas-analyser}"
-KLAB_OUT="${KLAB_OUT:-out}"
 
-GAS_DIR=$KLAB_OUT/gas
-cd "$GAS_DIR" || exit
+if [ -z "$KLAB_OUT" ]; then
+  KLAB_OUT=out
+fi
+export GAS_DIR=$KLAB_OUT/gas
 
-shopt -s nullglob #disable null globbing
-for rawgasfile in *.raw.kast.json; do
-    echo "Consuming ending gas expression from $GAS_DIR/$rawgasfile..."
-    OUTNAME=$(basename "$rawgasfile" .raw.kast.json).kast
-    $GAS_SOLVER --input "$rawgasfile" > "$OUTNAME"
-    echo "Saved exact gas expression to $GAS_DIR/$OUTNAME"
-done
-shopt -u nullglob #revert nullglob
+if [ -z "$1" ]; then
+  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
+  if [ -z $spec_hash ]; then
+    echo "ERROR: $1 no spec or active HEAD found"
+    exit 1;
+  fi
+else
+  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
+    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  else
+    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
+      spec_hash="$1"
+    else
+      echo "ERROR: $1 is unknown"
+      exit 1;
+    fi;
+  fi;
+fi
+
+klab gas-analyser --input "$GAS_DIR/${spec_hash}.raw.kast.json" > "$GAS_DIR/${spec_hash}.kast"
+result=$?
+
+if [ $result -ne "0" ]; then
+  rm "$GAS_DIR/${spec_hash}.raw.kast.json"
+  exit 1;
+fi
diff --git a/libexec/klab-status b/libexec/klab-status
--- a/libexec/klab-status
+++ b/libexec/klab-status
@@ -1,107 +1,43 @@
-#!/usr/bin/env node
-// TODO - compile needs to carry on the act
+#!/usr/bin/env bash
 
-const fs = require("fs");
-const path = require("path");
-const {docopt}      = require("docopt");
-const {
-  testPath,
-  read,
-  ensureDir
-} = require("../lib/util.js");
-const { genBehaviour } = require("../lib/behavior.js");
-const format = require("../lib/format.js")
+red=$(tput setaf 1)
+green=$(tput setaf 2)
+yellow=$(tput setaf 3)
+bold=$(tput bold)
+reset=$(tput sgr0)
 
-const KLAB_OUT = process.env.KLAB_OUT || "out";
-const KLAB_WD_PATH = path.join(KLAB_OUT, "data");
+if [ -z "$KLAB_OUT" ]; then
+    export KLAB_OUT=out
+fi
 
-const {
-  prune_edges,
-} = require("../lib/compile.js");
+if [ -z "$1" ]; then
+  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
+  if [ -z $spec_hash ]; then
+    echo "ERROR: $1 no spec or active HEAD found"
+    exit 1;
+  fi
+else
+  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
+    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  else
+    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
+      spec_hash="$1"
+    else
+      echo "ERROR: $1 is unknown"
+      exit 1;
+    fi;
+  fi;
+fi
 
-const usage = `
-Usage:
-  klab status [options] <hash>
+name=$(jq -r ".name" < "$KLAB_OUT/meta/data/$spec_hash")
 
-Options:
-  --raw
-`
-const cmd = docopt(usage, {
-  argv: ["status"].concat(process.argv.slice(2))
-});
-
-const proofid = cmd['<hash>'];
-const RAW     = cmd['--raw'] || false;
-
-const {pruned_edges, initt, finished, steps} = prune_edges(proofid);
-const finished_ = finished
-  .reduce((a, node) => ({...a, [node]: true}), {});
-const steps_ = steps
-  .reduce((a, step) => { a[step] = true; return a; }, {});
-// generate coedges
-const coedges = Object.keys(pruned_edges)
-  .reduce((coedges, from) =>
-    pruned_edges[from]
-      .reduce((a, toO) => ({...a, [toO.to]: (a[toO.to]||[]).concat(toO)}), coedges)
-  , {})
-
-const meta_path = path.join(KLAB_OUT, 'meta', 'data', proofid);
-var meta = {};
-if(testPath(meta_path)) meta = JSON.parse(read(meta_path))
-
-const blobs = Object.keys(Object.keys(pruned_edges)
-  .map(ekey => pruned_edges[ekey]
-    .map(e => [e.from.split("_")[1], e.to.split("_")[1]])
-    .reduce((a, es) => a.concat(es), [])
-  )
-  .reduce((a, es) => a.concat(es), [])
-  .reduce((a, blob) => {a[blob] = true; return a;}, {}))
-
-const blobs_data = blobs
-  .map(blobid => [blobid, JSON.parse(read(path.join(KLAB_WD_PATH, `${proofid}_blobs`, blobid + ".json")))])
-  .reduce((a, [id, json]) => ({...a, [id]: json.term}), {})
-
-const state = {
-  edges: pruned_edges,      // done: klab compile-fsm
-  config: meta,
-  initt,                    // done: klab compile-fsm
-  finished: finished_,      // done: klab compile-fsm
-  steps: steps_,
-  nodes: blobs_data,
-  path: [{
-    "type": "step",
-    "count": 0,
-    "step": {
-      "from": "",
-      "to": initt,
-      "rule": ""
-    }
-  }]
-};
-
-const { behaviour } = genBehaviour(state);
-if(RAW) {
-  console.log(JSON.stringify(behaviour, false, 2));
-  process.exit();
-}
-
-state.status = behaviour.success
-  ? "ACCEPT"
-  : "REJECT"
-
-const styles = node => !node && 22
-  || node.branching && 215
-  || node.in_history && 255 // 77
-  || node.active && 244
-  || 234
-const table = format.foldPreorder({
-  tree: JSON.parse(JSON.stringify(behaviour)),
-  loc: "head",
-  styles
-})
-console.log("  " + format
-  .formatDb(table, ["head", "deltaC"], styles)
-  .split("\n")
-  .join("\n  ")
-  + "\n"
-)
+echo "$name"
+echo "$spec_hash "
+status="unknown"
+if [ -f "$KLAB_OUT/accept/$spec_hash" ]; then
+  status="${green}${bold}ACCEPT${reset}"
+fi;
+if [ -f "$KLAB_OUT/reject/$spec_hash" ]; then
+  status="${red}${bold}REJECT${reset}"
+fi;
+echo "status: $status"
diff --git a/libexec/klab-zip b/libexec/klab-zip
--- a/libexec/klab-zip
+++ b/libexec/klab-zip
@@ -1,29 +1,44 @@
 #!/usr/bin/env bash
 
 if [ -z "$KLAB_OUT" ]; then
-  echo "KLAB_OUT not set, defaulting to ./out/"
   KLAB_OUT=out
 fi
 
-if [ -f "$KLAB_OUT/meta/data/$1" ] ; then
-    spec_name=$(jq -r '.name' < "$KLAB_OUT/meta/data/$1")
+
+if [ -z "$1" ]; then
+  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
+  if [ -z $spec_hash ]; then
+    echo "ERROR: $1 no spec or active HEAD found"
+    exit 1;
+  fi
 else
-    spec_name="$1";
+  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
+    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  else
+    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
+      spec_hash="$1"
+    else
+      echo "ERROR: $1 is unknown"
+      exit 1;
+    fi;
+  fi;
 fi
+
+spec_name=$(jq -r ".name" < "$KLAB_OUT/meta/data/$spec_hash")
+
 
 if [ ! -d "$KLAB_OUT/log" ]; then
     mkdir -p "$KLAB_OUT/log"
 fi
 
-zip -r "$KLAB_OUT/log/$1.zip" \
-  config.json
+zip -r "$KLAB_OUT/log/$spec_hash.zip" config.json
 
 cd $KLAB_OUT
 find . \
-     \( -wholename "*$1*" -or -wholename "*$spec_name*" \) \
+     \( -wholename "*$spec_hash*" -or -wholename "*$spec_name*" \) \
      -and ! -wholename "*/log/*.zip" \
-     -exec zip "./log/$1.zip" {} +
+     -exec zip "./log/$spec_hash.zip" {} +
 
-zip -r "log/$1.zip" \
+zip -r "log/$spec_hash.zip" \
     "prelude.smt2" \
     "rules.k" \
