prove: configurable timeout
Adds a --timeout flag to `klab prove`, which is used by `klab prove-all`
to implement individual proof timeouts.

diff --git a/libexec/klab-prove b/libexec/klab-prove
--- a/libexec/klab-prove
+++ b/libexec/klab-prove
@@ -9,15 +9,18 @@ bold=$(tput bold)
 reset=$(tput sgr0)
 
 dump=false
-usage() { echo "Usage: klab prove [-d] [<spec>]" 1>&2; exit 1; }
-OPTS=$(getopt -o "d" -l "dump" -l "logs" -- "$@")
+logs=false
+TIMEOUT=1d
+usage() { echo "Usage: klab prove [-d|--dump] [--logs] [--timeout=<timeout>] [<spec>]" 1>&2; exit 1; }
+OPTS=$(getopt --name="$0" --options=d --longoptions="dump,logs,timeout:" -- "$@") || usage
 eval set -- "$OPTS"
 while true; do
   case "$1" in
-  -d | --dump) dump=true; shift;;
-  --logs)      logs=true; shift;;
-  --)           shift; break;;
-  *)            usage
+    --dump|-d) dump=true;  shift   ;;
+    --logs)    logs=true;  shift   ;;
+    --timeout) TIMEOUT=$2; shift 2 ;;
+    --) shift; break ;;
+    *) usage ;;
   esac
 done
 
@@ -30,7 +33,7 @@ if [ -z "$KLAB_EVMS_PATH" ]; then
 fi
 echo "Using evm-semantics from $KLAB_EVMS_PATH"
 
-if [ ! -z "$logs" ]; then
+if $logs; then
   mkdir -p "$KLAB_OUT/log/"
   STDOUT="$KLAB_OUT/log/$spec_hash.log"
   STDERR="$KLAB_OUT/log/$spec_hash.err.log"
@@ -46,26 +49,20 @@ if [ -z "$1" ]; then
     echo "ERROR: $1 no spec or active HEAD found"
     exit 1;
   fi
+elif [ -f "$KLAB_OUT/meta/name/$1" ]; then
+  spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
+  spec_name=$1
+elif [ -f "$KLAB_OUT/meta/data/$1" ]; then
+  spec_hash="$1"
+  spec_name=$(<"$KLAB_OUT/meta/data/$spec_hash" jq '.name' -r)
+elif [[ $1 =~ .k$ ]]; then
+  target_spec=$1
+  spec_hash=$(basename -s .k "$1")
+  spec_name=$(basename -s .k "$1")
 else
-  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
-    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
-    spec_name=$1
-  else
-    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
-      spec_hash="$1"
-      spec_name=$(<"$KLAB_OUT/meta/data/$spec_hash" jq '.name' -r)
-    else
-      if [[ $1 =~ .k$ ]]; then
-        target_spec=$1
-        spec_hash=$(basename -s .k "$1")
-        spec_name=$(basename -s .k "$1")
-      else
-        echo "ERROR: $1 is unknown"
-        exit 1;
-      fi;
-    fi;
-  fi;
-fi
+  echo "ERROR: $1 is unknown"
+  exit 1;
+fi;
 
 target_spec=${target_spec:-"$KLAB_OUT/specs/${spec_hash}.k"}
 
@@ -75,9 +72,12 @@ if $dump; then
   dump_notice="(with ${yellow}state logging${reset})"
 fi
 
-kprove() {
-  K_OPTS="$K_OPTS" \
-  "$KLAB_EVMS_PATH/deps/k/k-distribution/target/release/k/bin/kprove" \
+info="$(basename "$target_spec") [$spec_name] $dump_notice"
+echo "${blue}Proof ${bold}STARTING${reset}: $info"
+set +e
+trap 'echo "Trapped SIGTERM in klab-prove" && kill $kprove_child' TERM
+trap 'echo "Trapped SIGINT in klab-prove"  && kill $kprove_child' INT
+timeout "$TIMEOUT" "$KLAB_EVMS_PATH/deps/k/k-distribution/target/release/k/bin/kprove" \
   "${K_FLAGS[@]}" \
   --directory "$KLAB_EVMS_PATH/.build/defn/java/" \
   --def-module RULES \
@@ -91,40 +91,23 @@ kprove() {
   --boundary-cells k,pc \
   --smt_prelude "$KLAB_OUT/prelude.smt2" \
   --z3-tactic "(or-else (using-params smt :random-seed 3 :timeout 1000) (using-params smt :random-seed 2 :timeout 2000) (using-params smt :random-seed 1))" \
-  "$1"
-  exit $?
-}
-
-try_kill() {
-  if [ -n "$1" ]; then
-    echo "[prove] Sending SIGTERM to $1."
-    pkill -x "$1" && echo "[prove] Sent SIGTERM to $1." || echo "[prove] unable to kill $1"
-  fi;
-}
-
-_term() {
-  echo "[prove] Trapped SIG$(kill -l $?)."
-  try_kill "$kprove_child"
-}
-trap _term SIGTERM SIGINT
-
-echo "${blue}Proof ${bold}STARTING${reset}:" "$(basename "$target_spec")" "[$spec_name]" "$dump_notice"
-set +e
-kprove "$target_spec" >"$STDOUT" 2>"$STDERR" & kprove_child=$!
+  "$target_spec" >"$STDOUT" 2>"$STDERR" & kprove_child=$!
 wait "$kprove_child"
 result=$?
 unset kprove_child
 set -e
 
-if [ "$result" == "0" ]; then
-  echo "${green}Proof ${bold}ACCEPT${reset}:" "$(basename "$target_spec")" "[$spec_name]" "$dump_notice"
+if [ $result -eq 0 ]; then
   mkdir -p "$KLAB_OUT/accept" && touch "$KLAB_OUT/accept/$spec_hash"
-elif [ "$result" -eq "130" ]; then
+  echo "${green}Proof ${bold}ACCEPT${reset}: $info"
+elif [ $result -eq 124 ]; then
+  mkdir -p "$KLAB_OUT/timeout" && touch "$KLAB_OUT/timeout/$spec_hash";
+  echo "${red}Proof ${bold}TIMEOUT${reset}: $info"
+elif [ $result -gt 127 ]; then
   # results > 127 are 128 + signal number
-  echo "Abort: SIG$(kill -l $result)"
+  echo "Proof ${bold}ABORT${reset} $result SIG$(kill -l $result): $info"
 else
-  echo "${red}Proof $result ${bold}REJECT${reset}:" "$(basename "$target_spec")" "[$spec_name]" "$dump_notice"
   mkdir -p "$KLAB_OUT/reject" && touch "$KLAB_OUT/reject/$spec_hash"
+  echo "${red}Proof $result ${bold}REJECT${reset}: $info"
 fi
-
 exit $result
